title: Design Pattern Evangelist Blog
description: Smart Pointers For Software Design and Engineering
remote_theme: pages-themes/cayman@v0.2.0
future: true
plugins:
- jekyll-remote-theme
- jekyll-feed
defaults:
  -
    scope:
      path: ""
    values:
      comments: true
